import { ColumnDefinition } from "./types";

export const INITIAL_ROW_COUNT = 50;
export const MIN_EMPTY_TRAILING_ROWS = 5;
export const SELECTOR_COLUMN_WIDTH = 52;
export const MAX_CONCURRENT_BULK_REQUESTS = 4;
export const TRACKING_COLUMN_PATH = "detail.shipment_header.nomor_kiriman";
export const HIDDEN_COLUMNS_STORAGE_KEY = "shipflow-hidden-columns";
export const PINNED_COLUMNS_STORAGE_KEY = "shipflow-pinned-columns";
export const FILTER_PRESETS_STORAGE_KEY = "shipflow-filter-presets";

export const COLUMNS: ColumnDefinition[] = [
  {
    path: "detail.shipment_header.nomor_kiriman",
    label: "Nomor Kiriman",
    type: "text",
    defaultWidth: 200,
    minWidth: 160,
    sticky: true,
  },
  {
    path: "detail.actors.pengirim.nama",
    label: "Nama Pengirim",
    type: "text",
    defaultWidth: 220,
    minWidth: 180,
    tone: "pengirim",
  },
  {
    path: "detail.actors.pengirim.telepon",
    label: "Telepon Pengirim",
    type: "text",
    defaultWidth: 160,
    minWidth: 140,
  },
  {
    path: "detail.actors.pengirim.alamat",
    label: "Alamat Pengirim",
    type: "text",
    defaultWidth: 260,
    minWidth: 200,
  },
  {
    path: "detail.actors.penerima.nama",
    label: "Nama Penerima",
    type: "text",
    defaultWidth: 220,
    minWidth: 180,
    tone: "penerima",
  },
  {
    path: "detail.actors.penerima.telepon",
    label: "Telepon Penerima",
    type: "text",
    defaultWidth: 160,
    minWidth: 140,
  },
  {
    path: "detail.actors.penerima.alamat",
    label: "Alamat Penerima",
    type: "text",
    defaultWidth: 260,
    minWidth: 200,
  },
  {
    path: "detail.actors.penerima.kode_pos",
    label: "Kode Pos Penerima",
    type: "text",
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    path: "detail.shipment_header.booking_code",
    label: "Booking Code",
    type: "text",
    defaultWidth: 170,
    minWidth: 140,
  },
  {
    path: "detail.shipment_header.id_pelanggan_korporat",
    label: "ID Pelanggan Korporat",
    type: "text",
    defaultWidth: 170,
    minWidth: 140,
  },
  {
    path: "detail.origin_detail.nama_kantor",
    label: "Nama Kantor",
    type: "text",
    defaultWidth: 190,
    minWidth: 160,
  },
  {
    path: "detail.origin_detail.id_kantor",
    label: "ID Kantor",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.nama_petugas",
    label: "Nama Petugas",
    type: "text",
    defaultWidth: 180,
    minWidth: 150,
  },
  {
    path: "detail.origin_detail.id_petugas",
    label: "ID Petugas",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.tanggal_input",
    label: "Tanggal Input",
    type: "date",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.waktu_input",
    label: "Waktu Input",
    type: "text",
    defaultWidth: 120,
    minWidth: 110,
  },
  {
    path: "detail.package_detail.jenis_layanan",
    label: "Jenis Layanan",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "detail.package_detail.kriteria_kiriman",
    label: "Kriteria Kiriman",
    type: "text",
    defaultWidth: 190,
    minWidth: 150,
  },
  {
    path: "detail.package_detail.isi_kiriman",
    label: "Isi Kiriman",
    type: "text",
    defaultWidth: 230,
    minWidth: 180,
  },
  {
    path: "detail.package_detail.berat_actual",
    label: "Berat Actual",
    type: "weight",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.package_detail.berat_volumetric",
    label: "Berat Volumetric",
    type: "weight",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "detail.billing_detail.type_pembayaran",
    label: "Type Pembayaran",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "detail.billing_detail.bea_dasar",
    label: "Bea Dasar",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.nilai_barang",
    label: "Nilai Barang",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.htnb",
    label: "HTNB",
    type: "currency",
    defaultWidth: 120,
    minWidth: 110,
  },
  {
    path: "detail.billing_detail.cod_info.is_cod",
    label: "Is COD",
    type: "boolean",
    defaultWidth: 100,
    minWidth: 90,
  },
  {
    path: "detail.billing_detail.cod_info.virtual_account",
    label: "Virtual Account",
    type: "text",
    defaultWidth: 180,
    minWidth: 150,
  },
  {
    path: "detail.billing_detail.cod_info.total_cod",
    label: "Total COD",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.cod_info.status",
    label: "Status COD",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.cod_info.tanggal",
    label: "Tanggal COD",
    type: "date",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_target",
    label: "SLA Target",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_category",
    label: "SLA Category",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_days_diff",
    label: "SLA Days Diff",
    type: "number",
    defaultWidth: 120,
    minWidth: 100,
  },
];
