import { ColumnDefinition } from "./types";

export const INITIAL_ROW_COUNT = 50;
export const MIN_EMPTY_TRAILING_ROWS = 5;
export const SELECTOR_COLUMN_WIDTH = 52;
export const MAX_CONCURRENT_BULK_REQUESTS = 10;
export const TRACKING_COLUMN_PATH = "detail.shipment_header.nomor_kiriman";
export const DAYS_SINCE_TRANSACTION_COLUMN_PATH = "computed.days_since_transaction";
export const DAYS_SINCE_LAST_UNBAGGING_COLUMN_PATH =
  "computed.days_since_last_unbagging";
export const LATEST_BAG_STATUS_COLUMN_PATH = "history_summary.latest_bagging_status";
export const LATEST_MANIFEST_COLUMN_PATH = "history_summary.latest_manifest_r7";
export const LATEST_DELIVERY_COLUMN_PATH = "history_summary.latest_delivery_runsheet";
export const DELIVERY_RUNSHEET_COUNT_COLUMN_PATH =
  "computed.delivery_runsheet_count";
export const HIDDEN_COLUMNS_STORAGE_KEY = "shipflow-hidden-columns";
export const PINNED_COLUMNS_STORAGE_KEY = "shipflow-pinned-columns";
const NON_VALUE_FILTER_COLUMN_PATHS = new Set(["pod.photo1_url", "pod.photo2_url"]);

export function canUseColumnValueFilter(
  column: Pick<ColumnDefinition, "path" | "type">
) {
  return column.type !== "json" && !NON_VALUE_FILTER_COLUMN_PATHS.has(column.path);
}

export const ANALYTICS_FIELD_COLUMN_PATHS = [
  TRACKING_COLUMN_PATH,
  DAYS_SINCE_TRANSACTION_COLUMN_PATH,
  DAYS_SINCE_LAST_UNBAGGING_COLUMN_PATH,
  LATEST_BAG_STATUS_COLUMN_PATH,
  LATEST_MANIFEST_COLUMN_PATH,
  "status_akhir.status",
  "status_akhir.location",
  "status_akhir.officer_name",
  "status_akhir.officer_id",
  "status_akhir.date",
  "status_akhir.time",
  "detail.actors.pengirim.nama",
  "detail.actors.pengirim.telepon",
  "detail.actors.pengirim.alamat",
  "detail.actors.penerima.nama",
  "detail.actors.penerima.telepon",
  "detail.actors.penerima.alamat",
  "detail.actors.penerima.kode_pos",
  "detail.shipment_header.id_pelanggan_korporat",
  "detail.origin_detail.nama_kantor",
  "detail.origin_detail.id_kantor",
  "detail.origin_detail.nama_petugas",
  "detail.origin_detail.id_petugas",
  "detail.origin_detail.tanggal_input",
  "detail.package_detail.jenis_layanan",
  "detail.billing_detail.cod_info.is_cod",
  "detail.billing_detail.cod_info.total_cod",
  "detail.billing_detail.cod_info.status",
  "detail.performance_detail.sla_target",
  "detail.performance_detail.sla_category",
  "detail.performance_detail.sla_days_diff",
  DELIVERY_RUNSHEET_COUNT_COLUMN_PATH,
] as const;

export const COLUMNS: ColumnDefinition[] = [
  {
    path: "detail.shipment_header.nomor_kiriman",
    label: "Nomor Kiriman",
    type: "text",
    defaultWidth: 200,
    minWidth: 160,
    sticky: true,
  },
  {
    path: DAYS_SINCE_TRANSACTION_COLUMN_PATH,
    label: "TRX - TODAY",
    type: "number",
    defaultWidth: 132,
    minWidth: 124,
    maxWidth: 136,
    compact: true,
  },
  {
    path: DAYS_SINCE_LAST_UNBAGGING_COLUMN_PATH,
    label: "TRX - UNBAG",
    type: "number",
    defaultWidth: 132,
    minWidth: 124,
    maxWidth: 136,
    compact: true,
  },
  {
    path: LATEST_BAG_STATUS_COLUMN_PATH,
    label: "PID/Kantong Terakhir",
    type: "text",
    defaultWidth: 210,
    minWidth: 180,
  },
  {
    path: LATEST_MANIFEST_COLUMN_PATH,
    label: "Manifest Terakhir",
    type: "text",
    defaultWidth: 190,
    minWidth: 160,
  },
  {
    path: LATEST_DELIVERY_COLUMN_PATH,
    label: "Delivery Terakhir",
    type: "text",
    defaultWidth: 320,
    minWidth: 240,
  },
  {
    path: "status_akhir.status",
    label: "Status Akhir",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
    tone: "status",
  },
  {
    path: "status_akhir.location",
    label: "Lokasi Akhir",
    type: "text",
    defaultWidth: 220,
    minWidth: 180,
  },
  {
    path: "status_akhir.officer_name",
    label: "Petugas Akhir",
    type: "text",
    defaultWidth: 180,
    minWidth: 150,
  },
  {
    path: "status_akhir.officer_id",
    label: "ID Petugas Akhir",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "status_akhir.date",
    label: "Tanggal Status Akhir",
    type: "text",
    defaultWidth: 170,
    minWidth: 150,
  },
  {
    path: "status_akhir.time",
    label: "Waktu Status Akhir",
    type: "text",
    defaultWidth: 160,
    minWidth: 140,
  },
  {
    path: "detail.actors.pengirim.nama",
    label: "Nama Pengirim",
    type: "text",
    defaultWidth: 220,
    minWidth: 180,
    tone: "pengirim",
  },
  {
    path: "detail.actors.pengirim.telepon",
    label: "Telepon Pengirim",
    type: "text",
    defaultWidth: 160,
    minWidth: 140,
  },
  {
    path: "detail.actors.pengirim.alamat",
    label: "Alamat Pengirim",
    type: "text",
    defaultWidth: 260,
    minWidth: 200,
  },
  {
    path: "detail.actors.penerima.nama",
    label: "Nama Penerima",
    type: "text",
    defaultWidth: 220,
    minWidth: 180,
    tone: "penerima",
  },
  {
    path: "detail.actors.penerima.telepon",
    label: "Telepon Penerima",
    type: "text",
    defaultWidth: 160,
    minWidth: 140,
  },
  {
    path: "detail.actors.penerima.alamat",
    label: "Alamat Penerima",
    type: "text",
    defaultWidth: 260,
    minWidth: 200,
  },
  {
    path: "detail.actors.penerima.kode_pos",
    label: "Kode Pos Penerima",
    type: "text",
    defaultWidth: 150,
    minWidth: 120,
  },
  {
    path: "detail.shipment_header.booking_code",
    label: "Booking Code",
    type: "text",
    defaultWidth: 170,
    minWidth: 140,
  },
  {
    path: "detail.shipment_header.id_pelanggan_korporat",
    label: "ID Pelanggan Korporat",
    type: "text",
    defaultWidth: 170,
    minWidth: 140,
  },
  {
    path: "detail.origin_detail.nama_kantor",
    label: "Nama Kantor",
    type: "text",
    defaultWidth: 190,
    minWidth: 160,
  },
  {
    path: "detail.origin_detail.id_kantor",
    label: "ID Kantor",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.nama_petugas",
    label: "Nama Petugas",
    type: "text",
    defaultWidth: 180,
    minWidth: 150,
  },
  {
    path: "detail.origin_detail.id_petugas",
    label: "ID Petugas",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.tanggal_input",
    label: "Tanggal Input",
    type: "date",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.origin_detail.waktu_input",
    label: "Waktu Input",
    type: "text",
    defaultWidth: 120,
    minWidth: 110,
  },
  {
    path: "detail.package_detail.jenis_layanan",
    label: "Jenis Layanan",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
    tone: "layanan",
  },
  {
    path: "detail.package_detail.kriteria_kiriman",
    label: "Kriteria Kiriman",
    type: "text",
    defaultWidth: 190,
    minWidth: 150,
  },
  {
    path: "detail.package_detail.isi_kiriman",
    label: "Isi Kiriman",
    type: "text",
    defaultWidth: 230,
    minWidth: 180,
  },
  {
    path: "detail.package_detail.berat_actual",
    label: "Berat Actual",
    type: "weight",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.package_detail.berat_volumetric",
    label: "Berat Volumetric",
    type: "weight",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "detail.billing_detail.type_pembayaran",
    label: "Type Pembayaran",
    type: "text",
    defaultWidth: 150,
    minWidth: 130,
  },
  {
    path: "detail.billing_detail.bea_dasar",
    label: "Bea Dasar",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.nilai_barang",
    label: "Nilai Barang",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.htnb",
    label: "HTNB",
    type: "currency",
    defaultWidth: 120,
    minWidth: 110,
  },
  {
    path: "detail.billing_detail.cod_info.is_cod",
    label: "Is COD",
    type: "boolean",
    defaultWidth: 100,
    minWidth: 90,
    tone: "cod",
  },
  {
    path: "detail.billing_detail.cod_info.virtual_account",
    label: "Virtual Account",
    type: "text",
    defaultWidth: 180,
    minWidth: 150,
  },
  {
    path: "detail.billing_detail.cod_info.total_cod",
    label: "Total COD",
    type: "currency",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.cod_info.status",
    label: "Status COD",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.billing_detail.cod_info.tanggal",
    label: "Tanggal COD",
    type: "date",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_target",
    label: "SLA Target",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_category",
    label: "SLA Category",
    type: "text",
    defaultWidth: 140,
    minWidth: 120,
  },
  {
    path: "detail.performance_detail.sla_days_diff",
    label: "SLA Days Diff",
    type: "number",
    defaultWidth: 120,
    minWidth: 100,
  },
  {
    path: "pod.photo1_url",
    label: "POD Photo 1",
    type: "text",
    defaultWidth: 240,
    minWidth: 200,
  },
  {
    path: "pod.photo2_url",
    label: "POD Photo 2",
    type: "text",
    defaultWidth: 240,
    minWidth: 200,
  },
  {
    path: "history_summary.irregularity",
    label: "History Summary Irregularity",
    type: "json",
    defaultWidth: 300,
    minWidth: 240,
  },
  {
    path: "history_summary.bagging_unbagging",
    label: "History Summary Bagging Unbagging",
    type: "json",
    defaultWidth: 320,
    minWidth: 260,
  },
  {
    path: "history_summary.manifest_r7",
    label: "History Summary Manifest R7",
    type: "json",
    defaultWidth: 300,
    minWidth: 240,
  },
  {
    path: "history_summary.delivery_runsheet",
    label: "History Summary Delivery Runsheet",
    type: "json",
    defaultWidth: 320,
    minWidth: 260,
  },
  {
    path: DELIVERY_RUNSHEET_COUNT_COLUMN_PATH,
    label: "Jumlah Delivery Runsheet",
    type: "number",
    defaultWidth: 160,
    minWidth: 150,
    maxWidth: 170,
    compact: true,
  },
];
